variable "aws_region" {}
variable "alias_region" {}
variable "aws_profile" {}
variable "vpc_cidr" {}
variable "cidrs" {}
variable "localip" {}
variable "domain_name" {}
variable "db_instance_class" {}
variable "dbname" {}
variable "dbuser" {}
variable "dbpassword" {}
variable "key_name" {}
variable "public_key_path" {}
variable "dev_ami" {}
variable "dev_instance_type" {}
